### ISSUE TITLE
Deploy is not working

### ISSUE THREAD

**Issue by samuelteixeiras** [IBM-Bluemix/doctor-watson#11]
I tried make deploy using the deploy button. 
Give an error when bluemix try clone the repository,
http://imgur.com/XxD7jSj

**Comment by jthomas** [comment]
Unfortunately, this demo application doesn't work anymore due to the deprecation of the Q&A service.
We've left the code here to show the integration with Twilio etc. 
It won't deploy or work I'm afraid.

**Comment by samuelteixeiras** [comment]
You could add this information in the readme file.  :smile: thanks.

**Comment by jthomas** [comment]
I've just opened a pull request (#12) to add this, apologies!
