### ISSUE TITLE
Can't deploy to Bluemix

### ISSUE THREAD

**Issue by mamacdon** [IBM-Bluemix/doctor-watson#13]
Clicking the 'Deploy to Bluemix' button fails at the 'Repository cloning' step. 

The underlying cause appears to be the Twilio service:

```
{
  "code": 10001,
  "description": "Service broker error: This service cannot be created via the CLI.  Create this service using the Bluemix console.",
  "error_code": "CF-ServiceBrokerBadResponse",
}
```

**Comment by jthomas** [comment]
Unfortunately, this demo app doesn't work anymore due to the deprecation of the IBM Watson Q & A API. We've leaving the code up as a reference on integration Twilio with IBM Watson services.
